"""add direction and make category nullable

Revision ID: 0e4b1d62c329
Revises: 471ad6bd6002
Create Date: 2026-08-04 00:54:36.840356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4b1d62c329'
down_revision: Union[str, None] = '471ad6bd6002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('money_entries', sa.Column('direction', sa.String(), nullable=True))
    op.alter_column('money_entries', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('money_entries', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('money_entries', 'direction')
    # ### end Alembic commands ###
