"""adds the role to the portfolio table

Revision ID: 5500ced7a418
Revises: 0e4b1d62c329
Create Date: 2026-08-17 17:35:15.066944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5500ced7a418'
down_revision: Union[str, None] = '0e4b1d62c329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('role', sa.String(), nullable=True))
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.drop_column('portfolios', 'role')
    # ### end Alembic commands ###
